db:
  image: oracle/database:11.2.0.2-xe
  ports:
    - 1521:1521
    - 8085:8080
  shm_size: 1g
  volumes:
    - ./data:/u01/app/oracle/oradata
  environment:
    - ORACLE_PWD=<password>
  restart: unless-stopped
